[config]
deadzone_mode = axial
deadzone = 2000
deadzone_triggers = 3000

[controls]
# Residual default keyboard bindings: WASD, X, Escape, Tab, V.
back = esc
start = esc
a = x
b = w
x = tab
y = v
up = w
down = s
left = a
right = d
l1 = tab
r1 = x
l2 = v
r2 = s
left_analog_up = w
left_analog_down = s
left_analog_left = a
left_analog_right = d
